title: Chris Alexiou
author: Chris Alexiou
email: c@christos.id
url: https://christos.id
baseurl: ""
description: >
  Ops person. Software janitor.

permalink: /:slug.html

favicon: "logo.png"

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false
  lowercase_titles: true

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
